### ISSUE TITLE
Installation problem on new BK-CI-DATA4 server

### ISSUE THREAD

**Issue by stephenmcconnachie** [bfidatadigipres/bfi_universal_viewer#1]
@rwhscott I'm having an issue when running `npm install` after cloning this to the new BK-CI-DATA4 server for IIIF.

Error:
`npm WARN lifecycle bfi-universal-viewer@1.0.0~postinstall: cannot run in wd bfi-universal-viewer@1.0.0 npm run copy (wd=/home/datadigipres/code/bfi_universal_viewer)`

Looks like this `postinstall` issue derives from the `scripts` block in `package.json`:
```
  "scripts": {
    "copy": "rimraf uv && cp -R node_modules/universalviewer/uv uv",
    "start": "npx serve -p 42001",
    "postinstall": "npm run copy"
  }
```

I guess the "postinstall" invokes the "copy" script, which - I think - is just deleting a uv folder in the top level, then copying the nested uv folder in node_modules/universalviewer/, into that top level.

Not sure why it's generating that 'cannot run' error, but the net effect seems to be faulted installation of the UV - if I ignore the warning and run `npm start` - the index.html is reachable so it gets served, but the UV is not instantiated.

**Comment by stephenmcconnachie** [comment]
I had a look at the package.json in the uv-examples repo: https://github.com/UniversalViewer/uv-examples/blob/master/js/package.json

```
"scripts": {
    "copy": "npm run copy-uv-assets && npm run copy-uv-dist-umd && npm run copy-uv-html && npm run copy-uv-css",
    "copy-uv-assets": "cp -R node_modules/universalviewer/dist/uv-assets ./",
    "copy-uv-dist-umd": "cp -R node_modules/universalviewer/dist/uv-dist-umd ./",
    "copy-uv-html": "cp -R node_modules/universalviewer/dist/uv.html ./",
    "copy-uv-css": "cp -R node_modules/universalviewer/dist/uv.css ./",
    "postinstall": "npm run copy",
    "start": "npx http-server ./ -o -c-1"
  }
```

Lots more copying going on, and no rimraf / rm -rf. 

It also invokes the postinstall _before_ the start, so tomorrow I might try copying that..

**Comment by rwhscott** [comment]
Interesting... I've just cloned to my MacBook without issue.

`"copy": "rimraf uv && cp -R node_modules/universalviewer/uv uv"`, comes from `package.json` in `uv-hello-world` rather than `uv-examples`, so the difference might be a red herring.

I saw this on stack overflow:
"If npm was invoked with root privileges, then it will change the uid to the user account or uid specified by the user config, which defaults to nobody. Set the unsafe-perm flag to run scripts with root privileges."

https://stackoverflow.com/questions/18136746/npm-install-failed-with-cannot-run-in-wd

So I'm thinking the script is being blocked due to installing via an account with root permissions?  In which case you'd still get the same result if you updated scripts as per above.

**Comment by stephenmcconnachie** [comment]
I bet that’s it Rob. In any case Digirati are intending to bundle our UV into the logging application, so we can troubleshoot it if that arises when they get into that.

**Comment by stephenmcconnachie** [comment]
@rwhscott I added the usafe-perm flag and repeated npm install, that sorted it, you were right....

**Comment by stephenmcconnachie** [comment]
I think it's moot for the Digirati deployment as it'll be a Docker image so none of this user hassle should apply..

**Comment by rwhscott** [comment]
Glad that helped.  I think we can close this now?

**Comment by stephenmcconnachie** [comment]
Yes, definitely
